#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa

# Signal hooks
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Setup spaces with label
yabai -m space 1 --label Code
yabai -m space 2 --label Web
yabai -m space 3 --label Chat
yabai -m space 4 --label Plan
yabai -m space 5 --label Misc

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice)$" manage=off
yabai -m rule --add app="^(iStat Menus|Stats|FaceTime|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="AppCleaner" app="^AppCleaner$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off

# Config rules
yabai -m config window_shadow off
yabai -m config window_border_blur off
yabai -m config --space 5 layout bsp
yabai -m config external_bar all:22:0
yabai -m config \
	layout stack \
	top_padding 0   \
	bottom_padding 0  \
	left_padding 0 \
	right_padding 0

# Rules for specific apps to launch and be managed by yabai
# Code
yabai -m rule --add app="^Alacritty$" space=1
yabai -m rule --add app="^kitty$" space=1
yabai -m rule --add app="^Wezterm$" space=1
yabai -m rule --add app="^OrbStack$" space=1
yabai -m rule --add app="^Sublime Text$" space=1
yabai -m rule --add app="^Visual Studio Code$" space=1

# Web
yabai -m rule --add app="^Brave Browser$" space=2
yabai -m rule --add app="^Firefox Developer Edition$" space=2
yabai -m rule --add app="^Firefox$" space=2
yabai -m rule --add app="^Google Chrome$" space=2
yabai -m rule --add app="^Microsoft Edge$" space=2
yabai -m rule --add app="^Min$" space=2
yabai -m rule --add app="^Safari$" space=2
yabai -m rule --add app="^Vivaldi$" space=2

# Social
yabai -m rule --add app="^Discord$" space=3
yabai -m rule --add app="^Messenger$" space=3
yabai -m rule --add app="^Messages$" space=3
yabai -m rule --add app="^Microsoft Teams" space=3
yabai -m rule --add app="^Skype$" space=3
yabai -m rule --add app="^Slack$" space=3
yabai -m rule --add app="^Telegram$" space=3
yabai -m rule --add app="^Zalo$" space=3
yabai -m rule --add app="^zoom.us$" space=3

#Plan
yabai -m rule --add app="^Calendar$" space=4
yabai -m rule --add app="^Mail$" space=4
yabai -m rule --add app="^Microsoft Outlook$" space=4
yabai -m rule --add app="^Obsidian$" space=4
yabai -m rule --add app="^Notion$" space=4
yabai -m rule --add app="^Notion Calendar$" space=4
yabai -m rule --add app="^Evernote$" space=4

# Misc
yabai -m rule --add app="^Postman$" space=5
yabai -m rule --add app="^XCode$" space=5
yabai -m rule --add app="^Notes$" space=5
yabai -m rule --add app="^Reminders$" space=5

yabai -m rule --add app="^Music$" space=5
yabai -m rule --add app="^Spotify$" space=5
yabai -m rule --add app="^VOX$" space=5
yabai -m rule --add app="^VLC$" space=5

yabai -m rule --add app="^Preview$" space=5
yabai -m rule --add app="^Microsoft Word$" space=5
yabai -m rule --add app="^Microsoft Excel$" space=5
yabai -m rule --add app="^Numbers$" space=5
yabai -m rule --add app="^Numi$" space=5

yabai -m rule --add app="^CGoban$" space=5
yabai -m rule --add app="^GoPanda2$" space=5
yabai -m rule --add app="^Steam$" space=5
yabai -m rule --add app="^Tygem$" space=5

# start up sketchybar
brew services restart felixkratz/formulae/sketchybar

echo "yabai configuration loaded.."
