# Configs
font_family      Liga SFMono Nerd Font
bold_font        Liga SFMono Nerd Font Bold
italic_font      Liga SFMono Nerd Font Regular Italic
bold_italic_font Liga SFMono Nerd Font Bold Italic
font_size 15.0
modify_font baseline 0
undercurl_style thin-dense

symbol_map U+f101-U+f114,U+f116-U+f25c nonicons
symbol_map U+F0001-U+F1af0 Hack Nerd Font
symbol_map U+F8FF,U+100000-U+1018C7 SF Pro

disable_ligatures cursor
hide_window_decorations titlebar-only
window_margin_width 4
cursor_blink_interval 0
macos_quit_when_last_window_closed no
macos_option_as_alt left
macos_colorspace default
macos_show_window_title_in window
repaint_delay 8
input_delay 1

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_activity_symbol 
tab_title_max_length 30
tab_title_template "{fmt.fg.red}{bell_symbol}{fmt.fg.tab} {index}: ({tab.active_oldest_exe}) {title} {activity_symbol}"

env PATH=/opt/homebrew/bin/:/usr/local/bin/:${PATH}

# Keymaps
map cmd+ctrl+, load_config_file
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+0 goto_tab 10
map cmd+t launch --type=tab --cwd=current
map cmd+n launch --type=os-window --cwd=current

# Theme
include current-theme.conf
