#!/usr/bin/env sh
#
source "$HOME/.config/sketchybar/colors.sh"

##
# Variables
#
ITEM_DIR="$HOME/.config/sketchybar/ui"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
PADDING=4
PADDING_LABEL=4

##
# Fonts
#
LABEL="JetBrainsMono Nerd Font Mono"
# FONT="SF Pro"
# NERD_FONT="Liga SFMono Nerd Font"
# SPECIAL_FONT="OperatorMono Nerd Font"

############## BAR ##############
sketchybar --bar \
	height=24 \
	blur_radius=0 \
	position=top \
	sticky=on \
	padding_left=4 \
	padding_right=4 \
	color=0xff000000 \
	font_smoothing=on

############# DEFAULTS #############
sketchybar --default \
	icon.color=0xff${NORD4:1} \
	icon.font="$LABEL:Bold:13" \
	icon.padding_left=$PADDING \
	icon.padding_right=2 \
	label.color=0xff${NORD4:1} \
	label.font="$LABEL:Bold:13" \
	label.padding_left=$PADDING_LABEL \
	label.padding_right=$PADDING_LABEL \
	drawing=on \
	updates=when_shown

############# LEFT ITEMS #############
source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"

############# RIGHT ITEMS #############
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/docker.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
