alias kafstart='kafka-server-start /usr/local/etc/kafka/server.properties'
alias kafstop='kafka-server-stop /usr/local/etc/kafka/server.properties'
alias zoostart='zkServer start'
alias zoostop='zkServer stop'
alias zoorestart='zkServer restart'